### ISSUE TITLE
Local Python Is Not Working

### ISSUE THREAD

**Issue by Jonah1234567** [Kings-Distributed-Systems/Bifrost#30] opened 2022-06-09 17:33 UTC
Running jobs with Bifrost from a local python environment is not currently functional. Test results from Windows 10 Environment with Node 16.15.0 and Python 3.8.8:

Code: 
```
from bifrost import dcp, node, npm

input_string = "Hello World"
# INPUT SET
input_set = list(input_string)
print(input_set)


node.run("console.log('hi')")


# WORK FUNCTION
def work_function(input_slice):
    return input_slice.upper()


# COMPUTE_FOR
job = dcp.compute_for(input_set, work_function)

# EXEC
result_set = job.exec()

# DISPLAY RESULTS
print(''.join(result_set))

```
Error:
```
Error: \\?\C:\Users\jonah\OneDrive\Desktop\DCL Work\Bifrost\node_modules\@raygun-nickj\mmap-io\build\binding\Release\node-v93-win32-x64\mmap_io.node is not a valid Win32 application.
\\?\C:\Users\jonah\OneDrive\Desktop\DCL Work\Bifrost\node_modules\@raygun-nickj\mmap-io\build\binding\Release\node-v93-win32-x64\mmap_io.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\jonah\OneDrive\Desktop\DCL Work\Bifrost\node_modules\@raygun-nickj\mmap-io\dist\mmap-io.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[WinError 5] Access is denied
Pipe broke and was restarted
Could not run script
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    result_set = job.exec()
  File "C:\Users\jonah\anaconda3\lib\site-packages\bifrost\Job.py", line 417, in exec
    results = self.__dcp_run()
  File "C:\Users\jonah\anaconda3\lib\site-packages\bifrost\Job.py", line 367, in __dcp_run
    result_set = node_output['jobOutput']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ccmcintyre-kingsds** [comment] 2022-06-11 21:33
This issue name and description are not ideal. The term "local python" is not meaningful here, though the subsequent clarification of OS+Node+Python environment is helpful and appreciated. Further, this ticket makes it unclear whether it is DCP deployments that are not working in that context, or Bifrost interop generally. We **cannot** conflate these two as a matter of course in this repo, and if the issue is with interop, then the minimum example (`node.run(...)`) will be a much shorter and clearer way of demonstrating that, as I have tried to emphasize in past. On a close look I can see that you are leading with exactly that here, actually, which is good to see; all the Compute API code which follows is strictly a distraction from that. Please be careful in future.

**Comment by ccmcintyre-kingsds** [comment] 2022-06-11 23:00
Closing as duplicate of #33 ("Broken Pipe Errors"), which was made later but with identical error output, and serves as a more precise and comprehensive description of the problem being encountered.

**Closed by ccmcintyre-kingsds** 2022-06-11 23:00 UTC
Labels: bug, duplicate
